### PR TITLE
Installation Guide

### PR DESCRIPTION
**Pull request by gupta-shrinath**
Installation guide to deploying bot in local machine.

### CODE REVIEW

**Comment by gupta-shrinath** [comment]
Hi @robinfriedli could you please look at this pull request and let me know if any changes are required.

**Comment by Ethanol6** [comment]
Sent you a pull request with some spelling and grammar fixes.

**Comment by gupta-shrinath** [comment]
@Ethanol6 Hi Ethan! Thanks for fixing those issues. I have updated the fork as well. Although I'm not really sure whether it will get merged because when I created this pull request, the bot was called Botify and now it is Aiode there might be changes to installation @robinfriedli is it good to go, or do we need to make any changes?

**Comment by robinfriedli** [comment]
The setup is very different for botify 2 / aiode with gradle and spring now, so the guide is quite obsolete.

**Comment by gupta-shrinath** [comment]
Thought so. I'll close this now.

**Pull request closed without merging**
